head:
  motor_ids: [20,21,22,23,24,25]
  use_motor_config: true
shoulder_left:
  motor_ids: [0,1,2,3,4,5,6,7,16,17]
  use_motor_config: true
shoulder_right:
  motor_ids: [8,9,10,11,12,13,14,15,18,19]
  use_motor_config: true
wrist_left:
  motor_ids: [26,27,28,29,30,31]
  use_motor_config: true
wrist_right:
  motor_ids: [32,33,34,35,36,37]
  use_motor_config: true
hand_right:
  motor_ids: [42,43,44,45]
  use_motor_config: true
hand_left:
  motor_ids: [38,39,40,41]
  use_motor_config: true
spine:
  motor_ids: [46,47,48,49,50,51]